name: Create Config File
on: 
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 检查服务器配置
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
    

    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget qemu-utils
        echo "-------------------------查看工作目录-------------------------"
        echo "当前位置："&& pwd
        echo "当前目录文件："&& ls -la
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 查看工作目录
      run: |
        echo "当前位置："&& pwd
        echo "当前目录文件："&& ls -la
    - name: 下载OpenWRT及其他包代码
      id: download_code
      run: |
        REPO_URL=https://github.com/openwrt/openwrt
        git clone $REPO_URL openwrt
        cd openwrt
        echo 所有分支：&&git branch -r
        echo 所有标签：&&git tag
        LATEST_BRANCH=$(git branch -r | sed 's/origin\///'|tail -n1)
        LATEST_TAG=$(git tag | grep -v 'rc'|tail -n1)
        echo 选择最新分支：$LATEST_BRANCH
        echo 选择最新非RC标签：$LATEST_TAG
        git checkout $LATEST_TAG
        rm -rf package/helloworld
        git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        git clone https://github.com/openwrt/packages.git ../gogogo
        sed -i 's/192.168.1.1/10.10.10.5/g' package/base-files/files/bin/config_generate
        sed -i 's/192.168./10.10./g' package/base-files/files/bin/config_generate
        sed -i 's/root:::0:99999:7:::/root:$1$DLXGbdIi$CnUIT65bKyIhDXfR520dZ.:0:0:99999:7:::/g' package/base-files/files/etc/shadow
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        rm -rf feeds/packages/lang/golang
        cp -r ../gogogo/lang/golang/ feeds/packages/lang/
        echo "repo_url=${REPO_URL}" >> $GITHUB_OUTPUT
        echo "latest_branch=${LATEST_BRANCH}" >> $GITHUB_OUTPUT
        echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
        echo "-------------------------查看工作目录-------------------------"
        echo "当前位置："&& pwd
        echo "当前目录文件："&& ls -la
    - name: 复制.config文件
      run: |
        cd openwrt
        mv ../config/x86_64.config .config
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: 生成diffconfig
      id: diff
      run: |
        cd openwrt
        ./scripts/diffconfig.sh > diffconfig
        echo "gentime=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT


    - name : 上传配置文件
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_Config_${{ steps.diff.outputs.gentime }}
        path: |
          openwrt/diffconfig
          openwrt/.config
